name: grabber
description: "Grabber is a simple and easy to use e-commerce app for your business. It is a mobile application that allows you to sell products online."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  faker: ^2.2.0
  toastification: ^3.0.3
  flutter_native_splash: ^2.4.6
  go_transitions: ^0.8.2
  go_router: ^16.1.0
  carousel_slider: ^5.1.1
  uuid: ^4.5.1
  add_to_cart_animation: ^2.0.4
  animated_digit: ^3.3.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
